pages / index / index;
zbzk / h5 / h5;
consulting / thirdParty / thirdParty;
halo / payPage / payPage;
filmPatch / payPage / payPage;
digitalImage / payPage / payPage;
takeNumber / payPage / payPage;
pages / outpatientPayment / outpatientPayment;
consulting / search / search;
consulting / doctorList / doctorList;
consulting / choosePatient / choosePatient;
consulting / selectBillProject / selectBillProject;
consulting / consultingList / consultingList;
consulting / myRight / myRight;
consulting / myPlusSource / myPlusSource;
physical / choosePatient / choosePatient;
patientTeam / teamDetail / teamDetail;
patientTeam / allTeam / allTeam;
pages / myDoctor / myDoctor;
pages / message / message;
consulting / doctorDetail / doctorDetail;
consulting / fastConsultPre / fastConsultPre;
pages / indoorNav / indoorNav;
hlsf / choosePatient / choosePatient;
cardiologyDepartment / choosePatient / choosePatient;
mdtConsult / mdtLogin / mdtLogin;
dayChemotherapy / choosePatient / choosePatient;
medicalMission / list / list;
actives / freeClinicIndex / freeClinic;
actives / hotAreaActivity / hotAreaActivity;
pages / bookRule / bookRule;
pages / queryReport / queryReport;
pages / userDetail / userDetail;
pages / patients / patients;
consulting / fastConsultDetail / fastConsultDetail;
consulting / activityDocList / activityDocList;
consulting / fastConsultDept / fastConsultDept;

// 新加
consulting/search/search;
pages/moreFeatures/moreFeatures;
takeNumber/choosePatient/choosePatient;
intelligentDiagnosis/choosePatient/choosePatient;
checkAppt/choosePatient/choosePatient;
pages/moreFeatures/moreFeatures;
pages/recordsList/recordsList;
coronavirus/orderList/orderList;
pages/userCenter/userCenter;
filmPatch/myAddressList/myAddressList;

